save_id: 6
outputs:
  out_value:
    type: audio
    label: Output
    tooltip: The current value in the sequence
controls:
  reset: Input
    type: trigger
    default: never
  sequence: ValueSequence
  ramping: FloatInRange
    min: 0
    max: 1
    default: 0
  timing_mode: TimingMode
    default_units: beats
  step_time: Duration
    default_format: fractional
    default: 1/4
gui: 
  label: Value Sequence
  category: Control
  tooltip: Outputs a customizable repeating pattern of values
  width: 8
  height: 4
  widgets:
    Input:
      y: 0
      control: reset
      label: Reset
      tooltip: When triggered, moves back to the start of the sequence
      icon: Factory:reset
    ValueSequence:
      x: 0
      y: 0
      w: 8
      h: 1
      sequence_control: sequence
      ramping_control: ramping
      tooltip: Drag a segment to change the value at that point in time
      feedback_name: playhead_feedback
    TimingSelector:
      x: 0
      y: 2
      control: timing_mode
    DurationBox:
      x: 2
      y: 2
      duration_control: step_time
      mode_control: timing_mode
      label: Step Time
      tooltip: How long one step of the sequence takes
    Knob:
      x: 4
      y: 2
      control: ramping
      label: Ramping
      tooltip: How smooth the transition between values should be
    ValueSequenceLength:
      x: 6
      y: 2
      sequence_control: sequence
      label: Num. Steps
      tooltip: The number of steps the sequence plays before repeating